"""initial

Revision ID: 0e409359fc6e
Revises: 1a5c3fe85dea
Create Date: 2023-11-27 09:52:36.909941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e409359fc6e'
down_revision: Union[str, None] = '1a5c3fe85dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('category', sa.String(), nullable=True))
    op.add_column('dishes', sa.Column('category_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_dishes_category'), 'dishes', ['category'], unique=False)
    op.create_index(op.f('ix_dishes_category_code'), 'dishes', ['category_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dishes_category_code'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_category'), table_name='dishes')
    op.drop_column('dishes', 'category_code')
    op.drop_column('dishes', 'category')
    # ### end Alembic commands ###
