"""initial

Revision ID: 3296b89f11f5
Revises: 3f39d6825685
Create Date: 2023-11-28 21:29:49.330074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3296b89f11f5'
down_revision: Union[str, None] = '3f39d6825685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('completedAt', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_completedAt'), 'orders', ['completedAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_completedAt'), table_name='orders')
    op.drop_column('orders', 'completedAt')
    # ### end Alembic commands ###
