"""adding-restaurant-relationship

Revision ID: 3df4de6b436c
Revises: dec3cc1d65f2
Create Date: 2023-11-22 05:35:42.605226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df4de6b436c'
down_revision: Union[str, None] = 'dec3cc1d65f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('restaurant_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'addresses', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_constraint('restaurants_address_id_key', 'restaurants', type_='unique')
    op.drop_constraint('restaurants_address_id_fkey', 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('address_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('restaurants_address_id_fkey', 'restaurants', 'addresses', ['address_id'], ['id'])
    op.create_unique_constraint('restaurants_address_id_key', 'restaurants', ['address_id'])
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'restaurant_id')
    # ### end Alembic commands ###
