"""initial

Revision ID: 3f39d6825685
Revises: ff36d632d947
Create Date: 2023-11-28 21:13:46.937012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f39d6825685'
down_revision: Union[str, None] = 'ff36d632d947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_payment'), 'orders', ['payment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_payment'), table_name='orders')
    op.drop_column('orders', 'payment')
    # ### end Alembic commands ###
