"""initial

Revision ID: 5ae7011d8d85
Revises: 
Create Date: 2023-11-21 19:34:56.314669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae7011d8d85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_code'), 'promotions', ['code'], unique=True)
    op.create_index(op.f('ix_promotions_cost'), 'promotions', ['cost'], unique=False)
    op.create_index(op.f('ix_promotions_count'), 'promotions', ['count'], unique=False)
    op.create_index(op.f('ix_promotions_createdAt'), 'promotions', ['createdAt'], unique=False)
    op.create_index(op.f('ix_promotions_description'), 'promotions', ['description'], unique=False)
    op.create_index(op.f('ix_promotions_duration'), 'promotions', ['duration'], unique=False)
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.create_index(op.f('ix_promotions_name'), 'promotions', ['name'], unique=False)
    op.create_index(op.f('ix_promotions_percentage'), 'promotions', ['percentage'], unique=False)
    op.create_index(op.f('ix_promotions_status'), 'promotions', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_createdAt'), 'users', ['createdAt'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('house_no', sa.String(), nullable=True),
    sa.Column('street1', sa.String(), nullable=True),
    sa.Column('street2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    op.create_index(op.f('ix_addresses_country'), 'addresses', ['country'], unique=False)
    op.create_index(op.f('ix_addresses_createdAt'), 'addresses', ['createdAt'], unique=False)
    op.create_index(op.f('ix_addresses_house_no'), 'addresses', ['house_no'], unique=False)
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_index(op.f('ix_addresses_latitude'), 'addresses', ['latitude'], unique=False)
    op.create_index(op.f('ix_addresses_longitude'), 'addresses', ['longitude'], unique=False)
    op.create_index(op.f('ix_addresses_postal_code'), 'addresses', ['postal_code'], unique=False)
    op.create_index(op.f('ix_addresses_state'), 'addresses', ['state'], unique=False)
    op.create_index(op.f('ix_addresses_street1'), 'addresses', ['street1'], unique=False)
    op.create_index(op.f('ix_addresses_street2'), 'addresses', ['street2'], unique=False)
    op.create_index(op.f('ix_addresses_type'), 'addresses', ['type'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('transportation_mode', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_createdAt'), 'profiles', ['createdAt'], unique=False)
    op.create_index(op.f('ix_profiles_first_name'), 'profiles', ['first_name'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_last_name'), 'profiles', ['last_name'], unique=False)
    op.create_index(op.f('ix_profiles_mobile_number'), 'profiles', ['mobile_number'], unique=False)
    op.create_index(op.f('ix_profiles_photo'), 'profiles', ['photo'], unique=False)
    op.create_index(op.f('ix_profiles_rating'), 'profiles', ['rating'], unique=False)
    op.create_index(op.f('ix_profiles_transportation_mode'), 'profiles', ['transportation_mode'], unique=False)
    op.create_index(op.f('ix_profiles_updatedAt'), 'profiles', ['updatedAt'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('issue', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_createdAt'), 'support_tickets', ['createdAt'], unique=False)
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_support_tickets_issue'), 'support_tickets', ['issue'], unique=False)
    op.create_index(op.f('ix_support_tickets_message'), 'support_tickets', ['message'], unique=False)
    op.create_index(op.f('ix_support_tickets_subject'), 'support_tickets', ['subject'], unique=False)
    op.create_table('user_promotion',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('promotion_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('restaurants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('address_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('delivery_fee', sa.Float(), nullable=True),
    sa.Column('min_delivery_time', sa.Integer(), nullable=True),
    sa.Column('max_delivery_time', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address_id')
    )
    op.create_index(op.f('ix_restaurants_createdAt'), 'restaurants', ['createdAt'], unique=False)
    op.create_index(op.f('ix_restaurants_delivery_fee'), 'restaurants', ['delivery_fee'], unique=False)
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_index(op.f('ix_restaurants_image'), 'restaurants', ['image'], unique=False)
    op.create_index(op.f('ix_restaurants_isActive'), 'restaurants', ['isActive'], unique=False)
    op.create_index(op.f('ix_restaurants_max_delivery_time'), 'restaurants', ['max_delivery_time'], unique=False)
    op.create_index(op.f('ix_restaurants_min_delivery_time'), 'restaurants', ['min_delivery_time'], unique=False)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.create_index(op.f('ix_restaurants_rating'), 'restaurants', ['rating'], unique=False)
    op.create_table('adverts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adverts_createdAt'), 'adverts', ['createdAt'], unique=False)
    op.create_index(op.f('ix_adverts_duration'), 'adverts', ['duration'], unique=False)
    op.create_index(op.f('ix_adverts_id'), 'adverts', ['id'], unique=False)
    op.create_index(op.f('ix_adverts_image'), 'adverts', ['image'], unique=False)
    op.create_index(op.f('ix_adverts_name'), 'adverts', ['name'], unique=False)
    op.create_index(op.f('ix_adverts_status'), 'adverts', ['status'], unique=False)
    op.create_table('baskets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baskets_createdAt'), 'baskets', ['createdAt'], unique=False)
    op.create_index(op.f('ix_baskets_id'), 'baskets', ['id'], unique=False)
    op.create_table('dishes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_createdAt'), 'dishes', ['createdAt'], unique=False)
    op.create_index(op.f('ix_dishes_description'), 'dishes', ['description'], unique=False)
    op.create_index(op.f('ix_dishes_id'), 'dishes', ['id'], unique=False)
    op.create_index(op.f('ix_dishes_image'), 'dishes', ['image'], unique=False)
    op.create_index(op.f('ix_dishes_name'), 'dishes', ['name'], unique=False)
    op.create_index(op.f('ix_dishes_price'), 'dishes', ['price'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('courier_id', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_createdAt'), 'orders', ['createdAt'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_total'), 'orders', ['total'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_cost'), 'subscriptions', ['cost'], unique=False)
    op.create_index(op.f('ix_subscriptions_createdAt'), 'subscriptions', ['createdAt'], unique=False)
    op.create_index(op.f('ix_subscriptions_duration'), 'subscriptions', ['duration'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_name'), 'subscriptions', ['name'], unique=True)
    op.create_index(op.f('ix_subscriptions_type'), 'subscriptions', ['type'], unique=False)
    op.create_table('basket_dishes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('basket_id', sa.String(), nullable=True),
    sa.Column('dish_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basket_dishes_createdAt'), 'basket_dishes', ['createdAt'], unique=False)
    op.create_index(op.f('ix_basket_dishes_id'), 'basket_dishes', ['id'], unique=False)
    op.create_index(op.f('ix_basket_dishes_quantity'), 'basket_dishes', ['quantity'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.String(), nullable=True),
    sa.Column('dish_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_createdAt'), 'favorites', ['createdAt'], unique=False)
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_type'), 'favorites', ['type'], unique=False)
    op.create_table('order_dishes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dish_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_dishes_createdAt'), 'order_dishes', ['createdAt'], unique=False)
    op.create_index(op.f('ix_order_dishes_id'), 'order_dishes', ['id'], unique=False)
    op.create_index(op.f('ix_order_dishes_quantity'), 'order_dishes', ['quantity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_dishes_quantity'), table_name='order_dishes')
    op.drop_index(op.f('ix_order_dishes_id'), table_name='order_dishes')
    op.drop_index(op.f('ix_order_dishes_createdAt'), table_name='order_dishes')
    op.drop_table('order_dishes')
    op.drop_index(op.f('ix_favorites_type'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_createdAt'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_basket_dishes_quantity'), table_name='basket_dishes')
    op.drop_index(op.f('ix_basket_dishes_id'), table_name='basket_dishes')
    op.drop_index(op.f('ix_basket_dishes_createdAt'), table_name='basket_dishes')
    op.drop_table('basket_dishes')
    op.drop_index(op.f('ix_subscriptions_type'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_name'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_duration'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_createdAt'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_cost'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_orders_total'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_createdAt'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_dishes_price'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_name'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_image'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_id'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_description'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_createdAt'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_baskets_id'), table_name='baskets')
    op.drop_index(op.f('ix_baskets_createdAt'), table_name='baskets')
    op.drop_table('baskets')
    op.drop_index(op.f('ix_adverts_status'), table_name='adverts')
    op.drop_index(op.f('ix_adverts_name'), table_name='adverts')
    op.drop_index(op.f('ix_adverts_image'), table_name='adverts')
    op.drop_index(op.f('ix_adverts_id'), table_name='adverts')
    op.drop_index(op.f('ix_adverts_duration'), table_name='adverts')
    op.drop_index(op.f('ix_adverts_createdAt'), table_name='adverts')
    op.drop_table('adverts')
    op.drop_index(op.f('ix_restaurants_rating'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_min_delivery_time'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_max_delivery_time'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_isActive'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_image'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_delivery_fee'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_createdAt'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_table('user_promotion')
    op.drop_index(op.f('ix_support_tickets_subject'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_message'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_issue'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_createdAt'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_profiles_updatedAt'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_transportation_mode'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_rating'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_photo'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_mobile_number'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_last_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_first_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_createdAt'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_addresses_type'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_street2'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_street1'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_postal_code'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_longitude'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_latitude'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_house_no'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_createdAt'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_country'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_createdAt'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_promotions_status'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_percentage'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_name'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_duration'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_description'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_createdAt'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_count'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_cost'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_code'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
