"""adding-restaurant-relationship

Revision ID: ccaa274c88ae
Revises: 3df4de6b436c
Create Date: 2023-11-22 06:21:53.190110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccaa274c88ae'
down_revision: Union[str, None] = '3df4de6b436c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
