"""removing-address_id_field

Revision ID: e61d83876bfe
Revises: 5ae7011d8d85
Create Date: 2023-11-21 19:35:51.405973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61d83876bfe'
down_revision: Union[str, None] = '5ae7011d8d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('restaurants_address_id_key', 'restaurants', type_='unique')
    op.drop_constraint('restaurants_address_id_fkey', 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('address_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('restaurants_address_id_fkey', 'restaurants', 'addresses', ['address_id'], ['id'])
    op.create_unique_constraint('restaurants_address_id_key', 'restaurants', ['address_id'])
    # ### end Alembic commands ###
