"""initial

Revision ID: ff36d632d947
Revises: 0e409359fc6e
Create Date: 2023-11-27 10:19:51.452776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff36d632d947'
down_revision: Union[str, None] = '0e409359fc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_code'), 'orders', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_code'), table_name='orders')
    op.drop_column('orders', 'code')
    # ### end Alembic commands ###
