name: CI
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Concourse CI Pipeline
      run: |
        curl -k -X POST \
          -H "Content-Type: application/json" \
          -d '{"ref": "refs/heads/master"}' \
          YOUR-CONCOURSE-TRIGGER-URL
